name: flight_booking_ui
description: This is a flight booking application for travelers around the world, It’s focus on simplicity of use and able to forecast prices.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #  Widgets
  modal_bottom_sheet: ^2.0.0
  dotted_border: ^2.0.0
  flutter_dash: ^0.0.1
  expansion_card: ^0.1.0
  auto_size_text: ^2.1.0
  responsive_flutter: ^0.0.4
  introduction_screen: ^2.1.0
  #  circular_check_box: ^1.0.4
  buttons_tabbar: ^1.0.1
  expansion_tile_card: ^2.0.0
  intl_phone_field: ^2.0.0
  pin_code_fields: ^7.1.0

  #  increase or decrease the number
  flutter_spinbox: ^0.5.2

  #  search
  flutter_typeahead: ^3.1.3
  country_list_pick: ^1.0.1+3

  #  date time
  syncfusion_flutter_datepicker: ^19.1.63-beta
  scrollable_clean_calendar: ^0.4.0
  date_picker_timeline: ^1.2.1
  flutter_datetime_picker:
    git:
      url: https://github.com/Realank/flutter_datetime_picker.git
      ref: master
  cupertino_date_textbox: ^1.0.0+3
  intl: ^0.17.0

  #  Icon
  flutter_icons: ^1.1.0
  font_awesome_flutter: ^9.0.0
  community_material_icon: ^5.4.55
  cupertino_icons: ^1.0.0

  # Image
  flutter_svg: ^0.22.0
  flutter_svg_provider: ^0.1.6


  #  other
  shared_preferences: ^2.0.5
  file_manager: ^1.0.0
  google_fonts: ^3.0.1
  #  flutter_screenutil: ^4.0.3+1





  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    #lang
    - lang/en.json
    - lang/vi.json

    # Images
    - assets/images/lywing-slash-screen.png
    - assets/images/facebook.svg
    - assets/images/facebook-24px.svg
    - assets/images/google.svg
    - assets/images/google-brands.svg
    - assets/images/apple-brands.svg
    - assets/images/Traveling-rafiki.svg
    - assets/images/Artboard1.svg
    - assets/images/lywing-slash-screen.svg
    - assets/images/VJ.png
    - assets/images/VJ-1.png
    - assets/images/Avatar.png

    # Image Empty
    - assets/images/image-empty/suitcases.svg
    - assets/images/image-empty/no-flight.svg
    - assets/images/image-empty/search.svg
    - assets/images/image-empty/lywing-slash-screen.svg

    # Image Language
    - assets/country-flags-image/english.svg
    - assets/country-flags-image/japan.svg
    - assets/country-flags-image/south-korea.svg
    - assets/country-flags-image/thailand.svg
    - assets/country-flags-image/vietnam.svg

    # Image Introduce
    - assets/images/introduce/Flight-Booking-bro.svg
    - assets/images/introduce/Flight-Booking-pana.svg
    - assets/images/introduce/Subscriber-bro.svg

    # Image Carriers
    - assets/images/carriers/5J.png
    - assets/images/carriers/AC.png
    - assets/images/carriers/AF.png
    - assets/images/carriers/B7.png
    - assets/images/carriers/BA.png
    - assets/images/carriers/CX.png
    - assets/images/carriers/DL.png
    - assets/images/carriers/EK.png
    - assets/images/carriers/JL.png
    - assets/images/carriers/KE.png
    - assets/images/carriers/QH.png
    - assets/images/carriers/QR.png
    - assets/images/carriers/TR.png
    - assets/images/carriers/UA.png
    - assets/images/carriers/VJ.png
    - assets/images/carriers/VN.png

    # Icons
    - assets/icons/Line.png
    - assets/icons/Line-3.png
    - assets/icons/Line-4.png
    - assets/icons/Invert-button.png
    - assets/icons/linedown-flights.png
    - assets/icons/lineright-flights.png
    - assets/icons/Oval.png
    - assets/icons/dotted-line.png
    - assets/icons/timelapse.png
    - assets/icons/bag-2.png
    - assets/icons/close.png
    - assets/icons/ios-person-add.png
    - assets/icons/Toolbar.png
    - assets/icons/Famale.png
    - assets/icons/men.png
    - assets/icons/credit-card.png
    - assets/icons/success.png
    - assets/icons/Accent.png
    - assets/icons/qrcode.png
    - assets/icons/lens-2.png
    - assets/icons/lens-4.png
    - assets/icons/visa-pay-logo.png

    # Icon tabs
    - assets/icons/tabs/backpack.png
    - assets/icons/tabs/binoculars.png
    - assets/icons/tabs/profile.png
    - assets/icons/tabs/search.png
    - assets/icons/tabs/shield-3.png

    # Icon explore
    - assets/icons/explore/date-2.png
    - assets/icons/explore/more.png

    # Icon my-trip
    - assets/icons/my-trip/long-arrow-right.png

    # Icon empty
    - assets/icons/empty/travel-insurance.png
    - assets/icons/empty/ticket-2.png
    - assets/icons/empty/plane.png

    # Icon modal-bottom-sheet
    - assets/icons/modal-bottom-sheet/adults.png
    - assets/icons/modal-bottom-sheet/infants.png
    - assets/icons/modal-bottom-sheet/checked-bags.png
    - assets/icons/modal-bottom-sheet/one-way.png
    - assets/icons/modal-bottom-sheet/multi-city.png
    - assets/icons/modal-bottom-sheet/close.png
    - assets/icons/modal-bottom-sheet/search.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
